apiVersion: v1
kind: Secret
metadata:
  name: playfair-secret
  namespace: playfair
type: Opaque
data:
  # These are example values - replace with your actual base64 encoded values
  POSTGRES_USER: cGxheWZhaXI=     # playfair
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password